### ISSUE TITLE
Returns of run

### ISSUE THREAD

**Issue by fbnrst** [fabianrost84/clasim#7]
I updated the documentation of `run`. I realised that the return value of `run` was not documented, yet. I wrote that it is a list of labelled cells. Did I document it correctly?

Further, I please make sure that `run` also returns the time for each measurement. This could be done like this:
```python
tt = [t for t in times for i in range(samples)]
```

**Comment by rodjul42** [comment]
run returns now a list of labelled cells and the corresponding list of times.
    Returns
    -------
    labeled cells : list
        A list containing numbers of labelled cells with size len(times)*samples.
    times: list
        A list containing time points of measuremnets with size len(times)*samples.
